import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { auth } from "~/server/auth/auth";
import { SessionProvider } from "next-auth/react";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  return (
    <html lang="en" className={`${GeistSans.variable} dark`}>
      <body>
        <NextTopLoader color="yellow" zIndex={9999} />
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
